import React from 'react';
import "./styles/APIPage.css";

export default function APIPage() {
    return (
        <div className="api-container">
            <h1>API Documentation</h1>
            <p>Welcome to the ArtifAI API! Use our API to integrate advanced AI-driven art recognition capabilities into your applications, enabling you to distinguish between artworks created by humans and those generated by AI technologies.</p>

            <h2>API Endpoint</h2>
            <p>The base URL for the API is:</p>
            <code>https://artifai.apps.austinjiang.com/detect</code>

            <h2>Request Format</h2>
            <p>To submit an image for analysis, send a POST request with the image encoded in base64 format. The request should include the following headers and body:</p>

            <h3>Example headers:</h3>
            <ul>
                <li><code>Content-Type: application/json</code></li>
                <li><code>Accept: application/json</code></li>
            </ul>

            <h3>Body:</h3>
            <p>Include the image data as a JSON object with the key 'image':</p>
            <code>{`{"image": "base64_encoded_image_string"}`}</code>

            <h2>Response Format</h2>
            <p>The API response will be in JSON format, containing fields such as:</p>
            <ul>
                <li><strong>heatmap:</strong> A base64 encoded string of the heatmap image.</li>
                <li><strong>predictions:</strong> Details about the prediction made by the model.</li>
                <li><strong>sources:</strong> An array of potential sources of the image uploaded.</li>
                <li><strong>error:</strong> Any error message encountered during the process.</li>
            </ul>

            <h2>Example Request and Response</h2>
            <p>Here is an example of how to make a request using JavaScript's Fetch API:</p>
            <pre>
                {`fetch('https://artifai.apps.austinjiang.com/detect', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
    },
    body: JSON.stringify({
        image: 'base64_encoded_image_string'
    })
})
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.error('Error:', error));`}
            </pre>

            <h2>Troubleshooting</h2>
            <p>If you encounter issues while using the API, ensure that:</p>
            <ul>
                <li>The image is correctly encoded in base64 format.</li>
                <li>The request headers are correctly set.</li>
                <li>You are sending requests to the correct API endpoint.</li>
            </ul>
            <p>For more detailed troubleshooting, please visit our <a href="https://github.com/AustinBoyuJiang/ArtifAI" target="_blank" rel="noopener noreferrer">GitHub</a> or contact our team.</p>

        </div>
    );
}
