import React from 'react';
import "./styles/FAQPage.css";

export default function FAQPage() {
    return (
        <div className="faq-container">
            <h1>FAQs</h1>
            <div className="faq-card">
                <h2>What is ArtifAI?</h2>
                <p>ArtifAI is a tool designed to distinguish between artworks created by humans and those generated by AI, addressing copyright and rights issues in the digital art world.</p>
            </div>
            <div className="faq-card">
                <h2>How can I use ArtifAI?</h2>
                <p>Users can access ArtifAI through our web platform. Simply upload an artwork, and the tool will analyze it and provide information on its likely origin. Also, users can ask any copyright-related question to the ArtifAI consultant.</p>
            </div>
            <div className="faq-card">
                <h2>How do I access the ArtifAI API?</h2>
                <p>You can access the ArtifAI API by using our published endpoint. For more details, check our <a href="/api">API documentation</a> for detailed guidance on how to format your requests and interpret responses.</p>
            </div>
            <div className="faq-card">
                <h2>Can I contribute to ArtifAI?</h2>
                <p>Yes, contributions are welcome! Visit our <a href="https://github.com/AustinBoyuJiang/ArtifAI" target="_blank" rel="noopener noreferrer">GitHub</a> to see how you can get involved in the project.</p>
            </div>
            <div className="faq-card">
                <h2>How does ArtifAI work?</h2>
                <p>ArtifAI uses advanced machine learning algorithms, specifically convolutional neural networks, to analyze and classify artworks based on their origin.</p>
            </div>
            <div className="faq-card">
                <h2>Is ArtifAI 100% accurate in distinguishing art origins?</h2>
                <p>While ArtifAI achieves a high level of accuracy, no tool can guarantee 100% accuracy due to the complexities and nuances in art. However, ArtifAI continuously improves as it learns from new data.</p>
            </div>
            <div className="faq-card">
                <h2>What types of artwork can ArtifAI analyze?</h2>
                <p>ArtifAI is designed to analyze a wide range of artwork, including paintings, illustrations, and 3D models, among others.</p>
            </div>
            <div className="faq-card">
                <h2>Will ArtifAI misclassify real photographs as AI-generated?</h2>
                <p>Due to the focus on artistic features, there's a possibility that highly realistic photographs might be classified as AI-generated. We are working to minimize such occurrences.</p>
            </div>
            <div className="faq-card">
                <h2>Is there a cost to use ArtifAI?</h2>
                <p>Currently, ArtifAI is available for free as part of our commitment to supporting artists and the art community.</p>
            </div>
        </div>
    );
}
